TRAIN:
  train_serial: '20240827_2153'

PREDICT: 
  gpu: 0
  seed: 40

BehaPulse:
  host : '192.9.200.141'
  port : 443
  protocol : 'https'

label_map_ko:
  empty : '비어있음'
  lie : '누워있음'
  sit : '앉아있음'
